General Utility Library for C++17: gul17::ThreadPool::TaskHandle< T > Class Template Reference
gul17::ThreadPool::TaskHandle< T > Class Template Reference
Detailed Description
template<typename T>
class gul17::ThreadPool::TaskHandle< T >
A handle for a task that has (or had) been enqueued on a ThreadPool.
A TaskHandle can be used to query the status of a task and to retrieve its result.
auto pool = make_thread_pool(1);
auto task = pool->add_task([]() { return 42; });
while (not task.is_complete())
{
    std::cout << "Waiting for task to complete...\n";
    sleep(0.1);
}
std::cout << "Task result: " << task.get_result() << "\n";
#include <ThreadPool.h>
Public Member Functions
TaskHandle ()
Default-construct an invalid TaskHandle.
TaskHandle (TaskId id, std::future< T > future, std::shared_ptr< ThreadPool > pool)
Construct a TaskHandle.
bool cancel ()
Remove the task from the queue if it is still pending.
T get_result ()
Block until the task has finished and return its result.
bool is_complete () const
Determine whether the task has completed.
TaskState get_state () const
Determine if the task is running, waiting to be started, completed, or has been canceled.
Constructor & Destructor Documentation
TaskHandle() [1/2]
template<typename T > gul17::ThreadPool::TaskHandle< T >::TaskHandle () inline
Default-construct an invalid TaskHandle.
This constructor creates an invalid TaskHandle which has no result and is not associated with a ThreadPool.
TaskHandle() [2/2]
template<typename T > gul17::ThreadPool::TaskHandle< T >::TaskHandle (TaskId id, std::future< T > future, std::shared_ptr< ThreadPool > pool) inline
Construct a TaskHandle.
This constructor is not meant to be used directly. Instead, TaskHandles are returned by the ThreadPool when a task is enqueued.
Parameters
id Unique ID of the task
future A std::future that will eventually contain the result of the task
pool A shared pointer to the ThreadPool that the task is associated with
Member Function Documentation
cancel()
template<typename T > bool gul17::ThreadPool::TaskHandle< T >::cancel () inline
Remove the task from the queue if it is still pending.
This call has no effect if the task is already running.
Returns
true if the task was removed from the queue, false if it was not found in the queue (e.g. because it is already running).
Exceptions
std::logic_error is thrown if the associated thread pool does not exist anymore.
get_result()
template<typename T > T gul17::ThreadPool::TaskHandle< T >::get_result () inline
Block until the task has finished and return its result.
If is_complete() == true, the result is available immediately. If the task finished by throwing an exception, get_result() rethrows this exception.
References gul17::bit_set().
get_state()
template<typename T > TaskState gul17::ThreadPool::TaskHandle< T >::get_state () const inline
Determine if the task is running, waiting to be started, completed, or has been canceled.
Exceptions
std::logic_error is thrown if the associated thread pool does not exist anymore.
Note
If you just need to find out if a task has finished running, prefer is_complete() over this function. It does not need to interact with the ThreadPool and is therefore slightly more performant.
References gul17::bit_set(), gul17::canceled, gul17::complete, and gul17::ThreadPool::TaskHandle< T >::is_complete().
is_complete()
template<typename T > bool gul17::ThreadPool::TaskHandle< T >::is_complete () const inline
Determine whether the task has completed.
This function returns true if the task has finished, either successfully or by throwing an exception. It returns false if the task is still running, waiting to be started, or has been canceled.
Note
is_complete() does not need to interact with the ThreadPool to determine the state of the task. It is therefore slightly more performant than get_state(), but does not deliver the same fine-grained information.
References gul17::bit_set().
Referenced by gul17::ThreadPool::TaskHandle< T >::get_state().
The documentation for this class was generated from the following file:
ThreadPool.h