General Utility Library for C++17: gul17/substring_checks.h
gul17/substring_checks.h
Detailed Description
Checking whether a string contains, ends with, or starts with another string.
Functions
constexpr bool gul17::contains (std::string_view haystack, std::string_view needle) noexcept
Determine whether a string contains another string.
constexpr bool gul17::contains (std::string_view haystack, char needle) noexcept
Determine whether a string contains a certain character.
constexpr bool gul17::ends_with (std::string_view str, std::string_view suffix) noexcept
Determine whether a string ends with another string.
constexpr bool gul17::ends_with (std::string_view str, char c) noexcept
Determine whether a string ends with a certain character.
constexpr bool gul17::starts_with (std::string_view str, std::string_view prefix) noexcept
Determine whether a string starts with another string.
constexpr bool gul17::starts_with (std::string_view str, char c) noexcept
Determine whether a string starts with a certain character.
constexpr bool gul17::equals_nocase (std::string_view str1, std::string_view str2) noexcept
Determine whether a string is equal to another one, making no distinction between upper and lower case ASCII characters.
constexpr bool gul17::contains_nocase (std::string_view haystack, std::string_view needle) noexcept
Determine whether a string contains another string.
constexpr bool gul17::contains_nocase (std::string_view haystack, char needle) noexcept
Determine whether a string contains a certain character.
constexpr bool gul17::ends_with_nocase (std::string_view str, std::string_view suffix) noexcept
Determine whether a string ends with another string.
constexpr bool gul17::ends_with_nocase (std::string_view str, char c) noexcept
Determine whether a string ends with a certain character.
constexpr bool gul17::starts_with_nocase (std::string_view str, std::string_view prefix) noexcept
Determine whether a string starts with another string.
constexpr bool gul17::starts_with_nocase (std::string_view str, char c) noexcept
Determine whether a string starts with a certain character.
Function Documentation
contains() [1/2]
constexpr bool gul17::contains (std::string_view haystack, char needle) inline constexpr noexcept
Determine whether a string contains a certain character.
The comparison is case sensitive.
Parameters
haystack The string in which to search.
needle The character that should be searched for.
Returns
true if haystack contains at least one occurrence of needle, false otherwise.
See also
contains(std::string_view, std::string_view), contains_nocase(std::string_view, char), ends_with(std::string_view, char), starts_with(std::string_view, char)
References gul17::bit_set().
contains() [2/2]
constexpr bool gul17::contains (std::string_view haystack, std::string_view needle) inline constexpr noexcept
Determine whether a string contains another string.
The comparison is case sensitive. If the searched-for string is empty, the result is true.
Parameters
haystack The string in which to search.
needle The string that should be searched for.
Returns
true if haystack contains at least one occurrence of needle, false otherwise.
See also
contains(std::string_view, char), contains_nocase(std::string_view, std::string_view), ends_with(std::string_view, std::string_view), starts_with(std::string_view, std::string_view)
References gul17::bit_set().
contains_nocase() [1/2]
constexpr bool gul17::contains_nocase (std::string_view haystack, char needle) inline constexpr noexcept
Determine whether a string contains a certain character.
The comparison is case insensitive as far as ASCII characters are concerned (C locale).
Parameters
haystack The string in which to search.
needle The character that should be searched for.
Returns
true if haystack contains at least one occurrence of needle, false otherwise.
Since
GUL version 1.7
See also
contains_nocase(std::string_view, std::string_view), contains(std::string_view, char), ends_with_nocase(std::string_view, char), starts_with_nocase(std::string_view, char)
References gul17::bit_set(), and gul17::lowercase_ascii().
contains_nocase() [2/2]
constexpr bool gul17::contains_nocase (std::string_view haystack, std::string_view needle) inline constexpr noexcept
Determine whether a string contains another string.
The comparison is case insensitive as far as ASCII characters are concerned (C locale). If the searched-for string is empty, the result is true.
Parameters
haystack The string in which to search.
needle The string that should be searched for.
Returns
true if haystack contains at least one occurrence of needle, false otherwise.
Note
This function does not allocate memory to buffer the case-transformed input strings. It might therefore have lower performance than combining contains() and lowercase_ascii().
Since
GUL version 1.7
See also
contains_nocase(std::string_view, char), contains(std::string_view, std::string_view), ends_with_nocase(std::string_view, std::string_view), starts_with_nocase(std::string_view, std::string_view)
References gul17::bit_set(), and gul17::lowercase_ascii().
ends_with() [1/2]
constexpr bool gul17::ends_with (std::string_view str, char c) inline constexpr noexcept
Determine whether a string ends with a certain character.
The comparison is case sensitive.
Parameters
str The string to be tested.
c The character to be looked for at the end of str.
Returns
true if str ends with c, false otherwise.
See also
ends_with(std::string_view, std::string_view), ends_with_nocase(std::string_view, char), starts_with(std::string_view, char), contains(std::string_view, char)
References gul17::bit_set().
ends_with() [2/2]
constexpr bool gul17::ends_with (std::string_view str, std::string_view suffix) inline constexpr noexcept
Determine whether a string ends with another string.
The comparison is case sensitive. If the searched-for suffix is empty, the result is true.
Parameters
str The full string to be tested.
suffix The suffix to be looked for at the end of str.
Returns
true if str ends with suffix, false otherwise.
See also
ends_with(std::string_view, char), ends_with_nocase(std::string_view, std::string_view), starts_with(std::string_view, std::string_view), contains(std::string_view, std::string_view)
References gul17::bit_set().
ends_with_nocase() [1/2]
constexpr bool gul17::ends_with_nocase (std::string_view str, char c) inline constexpr noexcept
Determine whether a string ends with a certain character.
The comparison is case insensitive as far as ASCII characters are concerned (C locale).
Parameters
str The string to be tested.
c The character to be looked for at the end of str.
Returns
true if str ends with c, false otherwise.
Since
GUL version 1.7
See also
ends_with_nocase(std::string_view, std::string_view), ends_with(std::string_view, char), starts_with_nocase(std::string_view, char), contains_nocase(std::string_view, char)
References gul17::bit_set(), and gul17::lowercase_ascii().
ends_with_nocase() [2/2]
constexpr bool gul17::ends_with_nocase (std::string_view str, std::string_view suffix) inline constexpr noexcept
Determine whether a string ends with another string.
The comparison is case insensitive as far as ASCII characters are concerned (C locale). If the searched-for suffix is empty, the result is true.
Parameters
str The full string to be tested.
suffix The suffix to be looked for at the end of str.
Returns
true if str ends with suffix, false otherwise.
Since
GUL version 1.7
See also
ends_with_nocase(std::string_view, char), ends_with(std::string_view, std::string_view), starts_with_nocase(std::string_view, std::string_view), contains_nocase(std::string_view, std::string_view)
References gul17::bit_set(), and gul17::lowercase_ascii().
equals_nocase()
constexpr bool gul17::equals_nocase (std::string_view str1, std::string_view str2) inline constexpr noexcept
Determine whether a string is equal to another one, making no distinction between upper and lower case ASCII characters.
In other terms, this function performs a case insensitive string comparison using the C locale.
Parameters
str1,str2 The two strings that should be compared.
Returns
true if the ASCII-lowercase versions of str1 and str2 are equal, or false otherwise.
Since
GUL version 2.1
See also
contains_nocase(std::string_view, std::string_view), ends_with_nocase(std::string_view, std::string_view), starts_with_nocase(std::string_view, std::string_view)
References gul17::bit_set(), and gul17::lowercase_ascii().
starts_with() [1/2]
constexpr bool gul17::starts_with (std::string_view str, char c) inline constexpr noexcept
Determine whether a string starts with a certain character.
The comparison is case sensitive.
Parameters
str The string to be tested.
c The character to be looked for at the beginning of str.
Returns
true if str starts with c, false otherwise.
See also
starts_with(std::string_view, std::string_view), starts_with_nocase(std::string_view, char), ends_with(std::string_view, char), contains(std::string_view, char)
References gul17::bit_set().
starts_with() [2/2]
constexpr bool gul17::starts_with (std::string_view str, std::string_view prefix) inline constexpr noexcept
Determine whether a string starts with another string.
The comparison is case sensitive. If the searched-for prefix is empty, the result is true.
Parameters
str The full string to be tested.
prefix The prefix to be looked for at the beginning of str.
Returns
true if str starts with prefix, false otherwise.
See also
starts_with(std::string_view, char), starts_with_nocase(std::string_view, std::string_view), ends_with(std::string_view, std::string_view), contains(std::string_view, std::string_view)
References gul17::bit_set().
starts_with_nocase() [1/2]
constexpr bool gul17::starts_with_nocase (std::string_view str, char c) inline constexpr noexcept
Determine whether a string starts with a certain character.
The comparison is case insensitive as far as ASCII characters are concerned (C locale).
Parameters
str The string to be tested.
c The character to be looked for at the beginning of str.
Returns
true if str starts with c, false otherwise.
Since
GUL version 1.7
See also
starts_with_nocase(std::string_view, std::string_view), starts_with(std::string_view, char), ends_with_nocase(std::string_view, char), contains_nocase(std::string_view, char)
References gul17::bit_set(), and gul17::lowercase_ascii().
starts_with_nocase() [2/2]
constexpr bool gul17::starts_with_nocase (std::string_view str, std::string_view prefix) inline constexpr noexcept
Determine whether a string starts with another string.
The comparison is case insensitive as far as ASCII characters are concerned (C locale). If the searched-for prefix is empty, the result is true.
Parameters
str The full string to be tested.
prefix The prefix to be looked for at the beginning of str.
Returns
true if str starts with prefix, false otherwise.
Since
GUL version 1.7
See also
starts_with_nocase(std::string_view, char), starts_with(std::string_view, std::string_view), ends_with_nocase(std::string_view, std::string_view), contains_nocase(std::string_view, std::string_view)
References gul17::bit_set(), and gul17::lowercase_ascii().