General Utility Library for C++17: gul17/case_ascii.h
gul17/case_ascii.h
Detailed Description
Converting ASCII characters to lowercase or uppercase.
Functions
constexpr char gul17::lowercase_ascii (char c) noexcept
Return the ASCII lowercase equivalent of the given character (or the unchanged character, if it is not an ASCII letter).
GUL_EXPORT std::string gul17::lowercase_ascii (std::string_view str)
Return a copy of the given string in which all ASCII characters are replaced by their lowercase equivalents.
GUL_EXPORT std::string & gul17::lowercase_ascii_inplace (std::string &str) noexcept
Replace all ASCII characters in a string by their lowercase equivalents.
constexpr char gul17::uppercase_ascii (char c) noexcept
Return the ASCII uppercase equivalent of the given character (or the unchanged character, if it is not an ASCII letter).
GUL_EXPORT std::string gul17::uppercase_ascii (std::string_view str)
Return a copy of the given string in which all ASCII characters are replaced by their uppercase equivalents.
GUL_EXPORT std::string & gul17::uppercase_ascii_inplace (std::string &str) noexcept
Replace all ASCII characters in a string by their uppercase equivalents.
Function Documentation
lowercase_ascii() [1/2]
constexpr char gul17::lowercase_ascii (char c) constexpr noexcept
Return the ASCII lowercase equivalent of the given character (or the unchanged character, if it is not an ASCII letter).
Parameters
c The original character.
Since
GUL version 1.2
See also
lowercase_ascii(std::string_view), lowercase_ascii_inplace(std::string &), uppercase_ascii(char)
References gul17::bit_set().
Referenced by gul17::contains_nocase(), gul17::contains_nocase(), gul17::ends_with_nocase(), gul17::ends_with_nocase(), gul17::equals_nocase(), gul17::lowercase_ascii(), gul17::lowercase_ascii_inplace(), gul17::starts_with_nocase(), and gul17::starts_with_nocase().
lowercase_ascii() [2/2]
std::string gul17::lowercase_ascii (std::string_view str)
Return a copy of the given string in which all ASCII characters are replaced by their lowercase equivalents.
Parameters
str The original string.
Since
GUL version 1.2
See also
lowercase_ascii(char), lowercase_ascii_inplace(std::string &), uppercase_ascii(std::string_view)
References gul17::bit_set(), and gul17::lowercase_ascii().
lowercase_ascii_inplace()
std::string & gul17::lowercase_ascii_inplace (std::string & str) noexcept
Replace all ASCII characters in a string by their lowercase equivalents.
This function modifies the original string and returns a reference to it (which may be helpful for chaining function calls).
Parameters
str The string to be modified.
Returns
a reference to the string argument.
Since
GUL version 1.2
See also
lowercase_ascii(char), lowercase_ascii(std::string_view), uppercase_ascii_inplace(std::string &)
References gul17::bit_set(), and gul17::lowercase_ascii().
uppercase_ascii() [1/2]
constexpr char gul17::uppercase_ascii (char c) constexpr noexcept
Return the ASCII uppercase equivalent of the given character (or the unchanged character, if it is not an ASCII letter).
Parameters
c The original character.
Since
GUL version 1.2
See also
uppercase_ascii(std::string_view), uppercase_ascii_inplace(std::string &), lowercase_ascii(char)
References gul17::bit_set().
Referenced by gul17::uppercase_ascii(), and gul17::uppercase_ascii_inplace().
uppercase_ascii() [2/2]
std::string gul17::uppercase_ascii (std::string_view str)
Return a copy of the given string in which all ASCII characters are replaced by their uppercase equivalents.
Parameters
str The original string.
Since
GUL version 1.2
See also
uppercase_ascii(char), uppercase_ascii_inplace(std::string &), lowercase_ascii(std::string_view)
References gul17::bit_set(), and gul17::uppercase_ascii().
uppercase_ascii_inplace()
std::string & gul17::uppercase_ascii_inplace (std::string & str) noexcept
Replace all ASCII characters in a string by their uppercase equivalents.
This function modifies the original string and returns a reference to it (which may be helpful for chaining function calls).
Parameters
str The string to be modified.
Returns
a reference to the string argument.
Since
GUL version 1.2
See also
uppercase_ascii(char), uppercase_ascii(std::string_view), lowercase_ascii_inplace(std::string &)
References gul17::bit_set(), and gul17::uppercase_ascii().